// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcxzbTssuvH1aAwbsyBhvYpH9rjIyuR5k',
    appId: '1:473907884157:web:cc62a23593440630f0c114',
    messagingSenderId: '473907884157',
    projectId: 'kutuphaneapp-c3881',
    authDomain: 'kutuphaneapp-c3881.firebaseapp.com',
    storageBucket: 'kutuphaneapp-c3881.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNtABg5-d-8PdusuBur7o1NfFZwgMAnTU',
    appId: '1:473907884157:android:56bd12a5c7ce909ef0c114',
    messagingSenderId: '473907884157',
    projectId: 'kutuphaneapp-c3881',
    storageBucket: 'kutuphaneapp-c3881.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwz-qKd6UY9O7Gttu7Wi_lZT9ebjIrtf0',
    appId: '1:473907884157:ios:98a20e2da36c9ddaf0c114',
    messagingSenderId: '473907884157',
    projectId: 'kutuphaneapp-c3881',
    storageBucket: 'kutuphaneapp-c3881.appspot.com',
    iosBundleId: 'com.example.biblioHubApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwz-qKd6UY9O7Gttu7Wi_lZT9ebjIrtf0',
    appId: '1:473907884157:ios:8e5063aa02f0532df0c114',
    messagingSenderId: '473907884157',
    projectId: 'kutuphaneapp-c3881',
    storageBucket: 'kutuphaneapp-c3881.appspot.com',
    iosBundleId: 'com.example.biblioHubApp.RunnerTests',
  );
}
